services:
  - type: web
    name: shree-amar-ganesh-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: JWT_SECRET_KEY
        value: AMGM_JWT_SECRET_TOKEN_AUTH_2026_SECURE_SHA256_KEY
      - key: MONGO_URI
        value: mongodb+srv://amarganesh11:amarganesh11@cluster0.wmuzdt1.mongodb.net/shree_amar_ganesh_db?retryWrites=true&w=majority&appName=Cluster0
      - key: DB_NAME
        value: shree_amar_ganesh_db
